+++
title = "Can Making Notes Be a Discipline? (On using org-roam and contemporary zettelkasten practices)"
date = 2026-05-12
draft = true
+++
#+title: Can Making Notes Be a Discipline? (On using org-roam and contemporary zettelkasten practices)

Late last year I returned to a more regular reading-and-writing practice following a nearly two-year hiatus from when I left academia.
Before that, in the summer, I read some of recent interest in note-taking systems inspired by Niklas Luhmann's zettelkasten, or slip-box.

* Thinking as an askesis with symbolic reference
The circumstances around my writing have changed, of course.
I no longer read and respond to what I take in with a motivation to publish, deliver a talk, or teach a class.
Yet those motivators did express the deeper purpose of critical writing: namely, to think.
What is it we do when we think?
We occupy a different place than ordinary, practical life.
We entertain a theoretical attitude that is an open-ended training regime requiring frequent honing and straining of one's sensitivities to what experience comprises including, crucially, those forms that are coextensive with experiences of reason. 
This different place, for me and for many, has increasingly been the making of notes.
But before I explain some of the practicalities, like the tools I use, how I use them, and how that compares with recent ideas about those tools, I think it would be helpful to dwell on what goes on in such a place.

"Thinking persons are transposed to a sphere dominated by a single exercise: to clarify the meaning of words, sentences, and sequences of phrases we may speak when we want to say something true" (Sloterdijk, /The Art of Philosophy/ ch.1).
According to Peter Sloterdijk, the fundamental exercise of the theoretical attitude is the preparation of language for expressing truth.
This is, essentially, a Platonic definition of thinking activity, of reasoning, in that it aims toward knowledge (/episteme/) in direct opposition to opinion (/doxa/).
Thought is the working through of language in order to mean truthfully, that is to say it works through and on language.
To mean is to intend, to direct oneself toward.
Thinking orients oneself toward the true.
But this process of orienting is less a turning around—as if the philosopher or critic merely turns their attention away from the false and toward truth—than it is a cultivating of the terrain that makes expression as such possible.
(Though perhaps there is good reason to connect thinking as orientation to conversion.)
One can think of gravitation on a plane in space and imagine the repeated exercise of thinking as shaping those forces of attraction so that when one moves, one's movement is directed by the modified curvature of the space rather than by a spontaneous force of will.

Writing as thinking is a practice of transforming habits of linguistic expression to tend toward truth.
Such transformation includes the transformation of the words themselves, as they are part and parcel of those habits of expression.
"To clarify the meaning of words, sentences, and sequences of phrases" is not a one-sided affair, whereby the thinker becomes better able to make sense of static phrases.
It is a process of customizing language, of creating new language.
Knowledge, as a lived practice, requires perpetual reproduction and novel creation.
This demand on language by thought is, for instance, of central importance to Whitehead's process philosophy.
In order to construct a cosmological scheme on a radically revised basis relative to substance-based philosophies, Whitehead had to contend with the basic subject-predicate structure of language that has conditioned philosophic speculation since Aristotle.
"Words and phrases must be stretched towards a generality foreign to their ordinary usage; and however such elements of language be stabilized as technicalities, they remain metaphors mutely appealing for an imaginative leap" (/PR/ 4).
Since thinking goes hand in hand with the symbolic reference (to generalize from written language) that serves as its medium, it is better to speak not of the demand on language by thought but of the demand on past thought by novel thinking.
Writing is a way to enact that demand and respond to it.
* From Note-Taking to Note-Making
My writing system as an academic largely depended on an object to prompt me into writing.
Once I was in the midst of a project, I could usually count on myself to worry away at it.
Regardless of what it was that got me writing, I wrote longform almost exclusively.
I would take detailed notes on a text, producing a collection of personal indices, summaries, and arguments, often expounding on some point for hundreds of words.
These notes would be saved in a single file named after the author and text.
I could then directly lift these summaries and arguments into a writing project or refer to them in seminars.
Since I tend to associate arguments and ideas with the objects that prompted me to make/have them, I had no problem relocating what I had written.
I on occasion wrote standalone notes ranging from a few hundred words to a couple thousand.
Perhaps they should be called "little drafts" instead of notes.
These, too, could be slotted into an article or dissertation chapter.
This workflow demanded, at least it did for me, a lot of uninterrupted attention.
Writing was itself what interrupted me: from reading or consuming some object of analysis or an unrelated activity like sleep.
My writing happened /in media res/.
This meant that my attention to an object was frequently interrupted by discursions.
Furthermore, I wrote notes that were auxiliary to external functions such as finding a reference, reviewing a text or concept, or storing my partial drafts for later compositions.

But my circumstances for writing have changed.
I have less time and less energy to devote to it, seeing as I am no longer paid to do so, and I don't have the same daily activities that fostered my writing.
In particular, I don't have quite so many incidental prompts to come up with arguments, which would occur in conversation, while teaching, and following the work of others.
I also no longer have the overarching professional need to conduct research and to publish.

My way of writing has changed to reflect this new circumstance of performing criticism explicitly for the sake of self-formation rather than professional output and performance.
Instead of writing with a mind toward some public-facing output, I write with a focus on this demand on past thought by novel thinking.
I now take fewer notes while reading (or watching or playing, etc.); and when I do take a note, it's brief, just enough to serve as a point of departure for later.
That's the idea: to come back and write notes as a separate activity.
Instead of producing this running log of notes in parallel with the object encountered, I prioritize a way of writing for which the notes are themselves the work.
Their purpose is no longer to serve as a reference for thinking that occurs due to some external motivator (to publish, to teach).
Their purpose is to be engaged with in the service of creating new notes.

The shift in prioritization fosters two practical disciplines: a discipline over attention and a discipline over motivation.
# Edit the below to not use the "note-taking" and "note-making" terms.
# Also remove repetition of the take short notes now for later, which was explained in previous paragraph.
Note-taking is a short-form record of considerations to return to, considerations which came up while encountering something.
Writing notes occurs in its own time, separate from the encounter.
I make notes based on the notes I have taken.
Even when I return to a full passage in a book or review a scene in a film, I do so with the order of attention inverted to how it was during the encounter.
The object no longer dominates the flow of experience; instead it is the composition of notes that shapes my experience of the object.
To digress from a work too early often means making unnecessary work for myself.
I end up writing things that, had I followed the object to its conclusion, I would not have felt the need to write at all.
In other words, when I do resist the urge to write in excess, I often find my question answered, my confusion undone, or my observation complicated.

My other practical reason for wanting to reinforce the distinction between note-taking and note-making is to decouple the motivation to write from the immediate response to what I am consuming.
If I am able to ground my writing in the notes I take quickly while consuming something as well as in existing notes I have "made," then I expect I will be more capable of prompting myself to write when I want to write as opposed to when something fortuitously evokes me to do so.

** Problems with Doto's GTD-inspired note-taking vs note-making
This splitting off of the creation of notes from the consumption of things echoes what Bob Doto calls note-making in contrast to note-taking: a way of writing for which the notes are themselves the work (Doto, /A System for Writing/).
This distinction is itself inspired by Sönke Ahrens's distinction between on one hand, literature notes or reference notes as well as fleeting notes, and on the other hand permanent notes.

In the first chapter, Doto quotes David Allen, the GTD guy: "The mind is for having ideas, not holding them."
While by "having" is surely meant "coming up with new," the word choice is telling because it belies the difference between having and holding.

- [[id:cb4b4aaa-fc28-4b14-bf11-0055198a03fb][to write in spite of the zettlekasten misses out on the point of having one]]
- [[id:e6c15758-360c-412c-8f55-554ab2e737d7][Ahrens contends that details get in the way of thinking]]
- [[id:b12d0326-d84c-4ec3-a403-8426090b273a][Ahrens distinguishes thinking from remembering]]
* ...
Yet to frame thinking as exercises in the manipulation of symbolic reference is to beg the question: what of the performances for which training prepares the exercitant?
As an academic, these were obvious: publications, talks, and teaching.
But the point of taking an ascetic perspective on writing is to recognize the very exercises as performances in their own right.


Sloterdijk: "every gesture carried out shapes its performer and determines their future state from the second occurrence on" (/YMCYL/ "Prospect").

Practice can be considered a self-contained process insofar as it refers to any gesture that...
