+++
title = "Zettelkasten Criticism"
date = 2026-05-12
draft = true
+++
* Contemporary zettelkasten discourse
A lot of the above resonates with what proponents of keeping a zettelkasten advocate.
The two basic operations are to write notes and to link them.
There's a lot of discussion in online forums about formalizing these operations into just the right system.
Sönke Ahrens in /How to Take Smart Notes/ presents Luhmann's zettelkasten with some references to research in education, psychology, and neuroscience, and renders it into steps and different categories of notes ("literature" or "reference" notes vs. "permanent" notes).
(As an aside, I found it an enjoyable book. Ahrens is, or perhaps used to be, an academic, with a doctorate in education, I believe. So his perspective is more interesting to me than typical productivity guru types, and his purpose of helping others maintain a life-long thinking practice comes across as genuine.)
I think Sasha Fast is correct to downplay such distinctions, as he does often in reply to people posting questions.

The primary motivation (and belief) to keeping a zettelkasten is that it is supposed to match how people typically think with an objective record of that thinking, such that the objective record becomes the place in which thinking occurs.
Ahrens begins his book with the observation that writing never starts with a blank page but, rather, extends whatever one has already written.
The zettelkasten formalizes this into the notes-creation process.
In order to make past writing extendable, notes are supposed to be limited to a single idea.
Linking to past notes...

Copying over my little drafts from when I wrote them in direct response to some object certainly expresses this point.
But it is a one-way transfer, which often exhausts the potential for that little draft to become novel thinking.
This is why I've been writing in a way that constantly engages with what I previously wrote and does so directly by linking to it.


Some of it I came to independently, and some of it I have adopted from those recommendations.
** Problems with Doto's GTD-inspired note-taking vs note-making
This splitting off of the creation of notes from the consumption of things echoes what Bob Doto calls note-making in contrast to note-taking: a way of writing for which the notes are themselves the work (Doto, /A System for Writing/).
This distinction is itself inspired by Sönke Ahrens's distinction between on one hand, literature notes or reference notes as well as fleeting notes, and on the other hand permanent notes.

In the first chapter, Doto quotes David Allen, the GTD guy: "The mind is for having ideas, not holding them."
While by "having" is surely meant "coming up with new," the word choice is telling because it belies the difference between having and holding.

- [[id:cb4b4aaa-fc28-4b14-bf11-0055198a03fb][to write in spite of the zettlekasten misses out on the point of having one]]
- [[id:e6c15758-360c-412c-8f55-554ab2e737d7][Ahrens contends that details get in the way of thinking]]
- [[id:b12d0326-d84c-4ec3-a403-8426090b273a][Ahrens distinguishes thinking from remembering]]
